# CSV indexes
REQ_NAME_IDX = 0
REQ_UNIT_TOTAL_IDX = 1
REQ_UNIT_LIMIT_IDX = 2
REQ_CREDIT_IDX = 3

SUBREQ_NAME_IDX = 0
SUBREQ_PARENT_IDX = 1
SUBREQ_UNIT_TOTAL_IDX = 2
SUBREQ_UNIT_LIMIT_IDX = 3
SUBREQ_CREDIT_IDX = 4

WARR_SUBREQ_NAME_IDX = 0
WARR_SUBREQ_PARENT_IDX = 1
WARR_SUBREQ_CATEGORY_IDX = 2
WARR_SUBREQ_UNIT_TOTAL_IDX = 3
WARR_SUBREQ_UNIT_LIMIT_IDX = 4
WARR_SUBREQ_CREDIT_IDX = 5